version: '3.8'

services:
  db:
    image: mariadb:10.6
    volumes:
      - db-data:/var/lib/mysql
    container_name: baltic-stocks-mariadb-dev
    environment:
      MYSQL_DATABASE: baltic-stock
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "13306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
  db-data: {}