version: '3.8'

services:
  db:
    image: mariadb:10.6
    volumes:
    - db_data:/var/lib/mysql
    container_name: baltic-stock-mariadb
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  server:
    image: stenal/baltic-stock-server
    container_name: baltic-stock-server
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 3306
      DB_HOST: db
      SENTRY_DSN: ${SENTRY_DSN}
    ports:
      - "12345:12345"
    depends_on:
      - db
    command: ["/wait-for-it.sh", "${DB_HOST}:3306", "--", "sh", "-c", "java -jar /app.jar --spring.profiles.active=prod"]


volumes:
  db_data: {}
