version: '3.7'

services:
  db:
    image: mariadb:10.5
    volumes:
    - db_data:/var/lib/mysql
    container_name: baltic-stock-mariadb
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    command: ['mysqld', '--character-set-server=utf8']
  server:
    image: stenal/baltic-stock-server
    container_name: baltic-stock-server
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 3306
      DB_HOST: db
    ports:
      - 12345:12345
    depends_on:
      - db
    command: ["/wait-for-it.sh", "${DB_HOST}:3306", "--", "sh", "-c", "java -jar /app.jar --spring.profiles.active=prod"]


volumes:
  db_data: {}
