name: Frontend - build and deploy

on:
  push:
    branches:
      - main
    paths:
      - "client/**" # limit workflow only to changes in frontend folder
      - ".github/workflows/server-cd.yml"
  pull_request:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/client-cd.yml"


defaults:
  run:
    working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v4

      - name: set up Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm install
        run: npm ci

      - name: check formatting (Prettier)
        run: npm run format

      - name: check TypeScript
        run: npm run compile

  publish:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: set up WARP (workaround for IPv6 on GitHub Actions)
        uses: fscarmen/warp-on-actions@v1.3
        with:
          stack: ipv6
          mode: client

      - name: checkout current repository
        uses: actions/checkout@v4

      - name: set up Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm install
        working-directory: ./client
        run: npm ci

      - name: build static assets
        env:
          VITE_API_URL: https://laane.xyz/stonks/api
        working-directory: ./client
        run: npm run build

      - name: setup SSH for Ansible
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/id_rsa
          echo -e "${{secrets.SSH_KEY}}" > /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/id_rsa
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts

      - name: run Ansible deployment playbook
        shell: bash
        working-directory: ./ansible
        run: |
          ansible-playbook -vv --private-key /home/runner/.ssh/id_rsa -u ${{secrets.SSH_USER}} -i ${{ secrets.SSH_HOST }}, frontend.yml

