name: Frontend - build and deploy

on:
  push:
    branches:
      - main
    paths:
      - "client/**" # limit workflow only to changes in frontend folder
      - ".github/workflows/server-cd.yml"
  pull_request:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/client-cd.yml"


defaults:
  run:
    working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v3

      - name: set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: npm install
        run: npm ci

      - name: check formatting (Prettier)
        run: npm run format

      - name: check linting (ESLint)
        run: npm run lint

      - name: compile TypeScript
        run: npm run compile

  publish:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v3

      - name: set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install
        working-directory: ./client
        run: npm ci

      - name: build static assets
        env:
          REACT_APP_API_URL: https://laane.xyz/stonks/api
        working-directory: ./client
        run: npm run build

      - name: deploy assets to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "client/build/**"
          target: "/var/www/stonks"
          strip_components: 2
