name: Frontend - build and deploy

on:
  push:
    branches:
      - master
    paths:
      - "client/**" # limit workflow only to changes in frontend folder
  pull_request:
    branches:
      - master
    paths:
      - "client/**"

defaults:
  run:
    working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v2

      - name: set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: npm install
        run: npm ci

      - name: check formatting with Prettier
        run: npm run format

      - name: compile TypeScript
        run: npm run compile

  publish:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v2

      - name: set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        working-directory: ./client
        run: npm ci

      - name: build static assets
        env:
          REACT_APP_API_URL: https://laane.xyz/stonks/api
          REACT_APP_GOOGLE_ANALYTICS_CODE: UA-162143380-1
        working-directory: ./client
        run: npm run build

      - name: deploy assets to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "client/build/**"
          target: "/var/www/stonks"
          strip_components: 2
